declare module '~imports'

declare module '@sindresorhus/slugify'
declare module '@mdx-js/tag'
declare module '@mdx-js/tag/dist/mdx-provider'
declare module 'array-sort'
declare module 'capitalize'
declare module 'callbag-observe'
declare module 'callbag-subject'
declare module 'react-router-hash-link'
