declare module '@sindresorhus/slugify'
declare module '@mdx-js/tag'
declare module '@mdx-js/tag/dist/mdx-provider'
declare module 'array-sort'
declare module 'capitalize'
declare module 'react-router-hash-link'
declare module 'react-copy-write'
