export { default as Edit } from 'react-feather/dist/icons/edit-2'
export { default as Sun } from 'react-feather/dist/icons/sun'
export { default as Menu } from 'react-feather/dist/icons/menu'
export { default as Github } from 'react-feather/dist/icons/github'
export { default as Search } from 'react-feather/dist/icons/search'
export { default as ChevronUp } from 'react-feather/dist/icons/chevron-up'
export { default as ChevronDown } from 'react-feather/dist/icons/chevron-down'
