exports.mockArgv = {
  typescript: false,
  propsParser: true,
  debug: true,
  hashRouter: false,
  native: false,
  codeSandbox: true,
  sourcemaps: true,
  base: '/',
  source: './',
  src: './',
  files: '**/*.mdx',
  ignore: [],
  public: '/public',
  dest: '.docz/dist',
  editBranch: 'master',
  config: '',
  title: 'Docz Example Basic',
  description: 'My awesome app using docz',
  theme: 'docz-theme-default',
  wrapper: null,
  indexHtml: null,
  ordering: 'descending',
  host: '127.0.0.1',
  port: 3000,
  websocketHost: '127.0.0.1',
  websocketPort: 60505,
  separator: '-',
}
